@TransactionsAPI_HostAddress = https://localhost:44353

GET {{TransactionsAPI_HostAddress}}/Users/GetUsers
Accept: application/json

###

GET {{TransactionsAPI_HostAddress}}/Api/Transactions
Accept: application/json
