@TransactionsAPI_HostAddress = https://localhost:44353

GET {{TransactionsAPI_HostAddress}}/weatherforecast/
Accept: application/json


###

GET {{TransactionsAPI_HostAddress}}/transaction/GetUser
Accept: application/json
